export const SCREEN_NAME = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  MAIN_SCREEN: 'MAIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  LOGIN_SOCIAL_SCREEN: 'LOGIN_SOCIAL_SCREEN',
};
